-- Q56: Fulfillment exception comment patterns
-- What do processors write when creating fulfillment exceptions?
USE ROLE ENG_PROVIDER;
USE DATABASE HEALTHSOURCE;
USE SCHEMA CONNEX;

SELECT
    r.EXCEPTION_REASON_DESC,
    UPPER(TRIM(e.EXCEPTION_COMMENT)) AS comment_normalized,
    COUNT(*) AS cnt
FROM erequest_exception e
JOIN erequest_exception_reason r
    ON e.EXCEPTION_REASON_ID = r.EREQUEST_EXCEPTION_REASON_ID
WHERE r.EXCEPTION_REASON_CODE LIKE 'FFEC001_%'
  AND e.CREATED_DT >= DATEADD(day, -90, CURRENT_DATE())
  AND e.EXCEPTION_COMMENT IS NOT NULL
  AND TRIM(e.EXCEPTION_COMMENT) <> ''
GROUP BY r.EXCEPTION_REASON_DESC, UPPER(TRIM(e.EXCEPTION_COMMENT))
HAVING COUNT(*) >= 20
ORDER BY r.EXCEPTION_REASON_DESC, cnt DESC;
